package com.kerite.pokedex.model.enums

enum class PokemonNature(
    val displayedName: String,
    val increasedStatistic: PokemonStatisticType? = null,
    val decreasedStatistic: PokemonStatisticType? = null,
    val likedFlavor: PokemonFlavor? = null,
    val hatedFlavor: PokemonFlavor? = null
) {
    HARDY("勤奋"),
    LONELY(
        "怕寂寞",
        PokemonStatisticType.ATTACK,
        PokemonStatisticType.DEFENCE,
        PokemonFlavor.SPICY,
        PokemonFlavor.SOUR
    ),
    ADAMANT(
        "固执",
        PokemonStatisticType.ATTACK,
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonFlavor.SPICY,
        PokemonFlavor.DRY
    ),
    NAUGHTY(
        "顽皮",
        PokemonStatisticType.ATTACK,
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonFlavor.SPICY,
        PokemonFlavor.BITTER
    ),
    BRAVE(
        "勇敢",
        PokemonStatisticType.ATTACK,
        PokemonStatisticType.SPEED,
        PokemonFlavor.SPICY,
        PokemonFlavor.SWEET
    ),
    BOLD(
        "大胆",
        PokemonStatisticType.DEFENCE,
        PokemonStatisticType.ATTACK,
        PokemonFlavor.SOUR,
        PokemonFlavor.SPICY
    ),
    DOCILE("坦率"),
    IMPISH(
        "淘气",
        PokemonStatisticType.DEFENCE,
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonFlavor.SOUR,
        PokemonFlavor.DRY
    ),
    LAX(
        "乐天",
        PokemonStatisticType.DEFENCE,
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonFlavor.SOUR,
        PokemonFlavor.BITTER
    ),
    RELAXED(
        "悠闲",
        PokemonStatisticType.DEFENCE,
        PokemonStatisticType.SPEED,
        PokemonFlavor.SOUR,
        PokemonFlavor.SWEET
    ),
    MODEST(
        "内敛",
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonStatisticType.ATTACK,
        PokemonFlavor.DRY,
        PokemonFlavor.SPICY
    ),
    MILD(
        "慢吞吞",
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonStatisticType.DEFENCE,
        PokemonFlavor.DRY,
        PokemonFlavor.SOUR
    ),
    BASHFUL("害羞"),
    RASH(
        "马虎",
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonFlavor.DRY,
        PokemonFlavor.BITTER
    ),
    QUIET(
        "冷静",
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonStatisticType.SPEED,
        PokemonFlavor.DRY,
        PokemonFlavor.SWEET
    ),
    CALM(
        "温和",
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonStatisticType.ATTACK,
        PokemonFlavor.BITTER,
        PokemonFlavor.SPICY
    ),
    GENTLE(
        "温顺",
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonStatisticType.DEFENCE,
        PokemonFlavor.BITTER,
        PokemonFlavor.SOUR
    ),
    CAREFUL(
        "慎重",
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonFlavor.BITTER,
        PokemonFlavor.DRY
    ),
    QUIRKY("浮躁"),
    SASSY(
        "自大",
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonStatisticType.SPEED,
        PokemonFlavor.BITTER,
        PokemonFlavor.SWEET
    ),
    TIMID(
        "胆小",
        PokemonStatisticType.SPEED,
        PokemonStatisticType.ATTACK,
        PokemonFlavor.SWEET,
        PokemonFlavor.SPICY
    ),
    HASTY(
        "急躁",
        PokemonStatisticType.SPEED,
        PokemonStatisticType.DEFENCE,
        PokemonFlavor.SWEET,
        PokemonFlavor.SOUR
    ),
    JOLLY(
        "爽朗",
        PokemonStatisticType.SPEED,
        PokemonStatisticType.SPECIAL_ATTACK,
        PokemonFlavor.SWEET,
        PokemonFlavor.DRY
    ),
    NAIVE(
        "天真",
        PokemonStatisticType.SPEED,
        PokemonStatisticType.SPECIAL_DEFENCE,
        PokemonFlavor.SWEET,
        PokemonFlavor.DRY
    ),
    SERIOUS("认真")
}